[package]
name = "stepper-permission"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }
globset = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
